const data = {
  products: [
    {
      name: 'Carrot - Orange',
      slug: 'carrot-orange',
      category: 'vegetables',
      image: '/images/carrot.png',
      quan: '250g',
      price: 22,
      countInStock: 20,
      description: 'Orange Carrots',
    },
    {
      name: 'Onion',
      slug: 'onion',
      category: 'vegetables',
      image: '/images/onion.png',
      quan: '1kg',
      price: 43,
      countInStock: 18,
      description: 'Onions',
    },
    {
      name: 'Tomato - Hybrid',
      slug: 'tomato-hybrid',
      category: 'vegetables',
      image: '/images/tomato.png',
      quan: '1kg',
      price: 28,
      countInStock: 23,
      description: 'Hybrid Tomatos',
    },
    {
      name: 'Potato',
      slug: 'potato',
      category: 'vegetables',
      image: '/images/potato.png',
      quan: '1kg',
      price: 46,
      countInStock: 15,
      description: 'Potatos',
    },
    {
      name: 'Coriander Leaves',
      slug: 'coriander-leaves',
      category: 'vegetables',
      image: '/images/coriander.png',
      quan: '100g',
      price: 9,
      countInStock: 26,
      description: 'Coriander Leaves',
    },
    {
      name: 'Banana - Yelakki',
      slug: 'banana-yelakki',
      category: 'fruits',
      image: '/images/banana.png',
      quan: '500g',
      price: 47,
      countInStock: 26,
      description: 'Banana - Yelakki',
    },
  ],
};

export default data;
